### ISSUE TITLE
Error on Assemble new config.toml

### ISSUE THREAD

**Issue by netcitylife** [riemers/ansible-gitlab-runner#88]
Hi.

Using latest 1.5.2 version, my variables:
```
gitlab_runner_coordinator_url: https://gitlab.***.ru/
gitlab_runner_registration_token: ***
gitlab_runner_runners:
  - name: pbx
    run_untagged: false
    tags:
      - production
      - vpbx
```

When installing, I get such error:
```
TASK [riemers.gitlab-runner : Copy gitlab-runner-wrapper.sh] *********************************************************************************************************************************************************************************
ok: [5.9.107.164]

TASK [riemers.gitlab-runner : Assemble new config.toml] **************************************************************************************************************************************************************************************
fatal: [5.9.107.164]: FAILED! => {"changed": false, "msg": "failed to validate: rc:1 error:Runtime platform                                  \u001b[0;m  arch\u001b[0;m=amd64 os\u001b[0;m=linux pid\u001b[0;m=16399 revision\u001b[0;m=577f813d version\u001b[0;m=12.5.0\nRunning in system-mode.                           \u001b[0;m \n                                                  \u001b[0;m \n\u001b[31;1mFATAL: toml: cannot load TOML value of type map[string]interface {} into a Go string\u001b[0;m \n"}
```

As I see this task just executes this command:
```
[root@pbx tmp]# /tmp/gitlab-runner-wrapper.sh /etc/gitlab-runner/config.toml
Runtime platform                                    arch=amd64 os=linux pid=3025 revision=577f813d version=12.5.0
Running in system-mode.                            
                                                   
Verifying runner... is alive                        runner=RszkNp8f
```

So return value seems to be OK and the runner itself is working OK as I can see. My configuration file config.toml:
```
[root@pbx tmp]# cat /etc/gitlab-runner/config.toml
concurrent = 8
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "pbx"
  output_limit = 4096
  url = "https://gitlab.***.ru/"
  token = "***"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
```

A can't figure out where is the problem, because everything seems to be OK except the errror... Thanks!

**Comment by richard-to** [comment]
Hmm if the assemble command failed that means it didn't write the latest config.toml.

You should run ansible playbook again with the `-v` or `-vv`. This will show you the temp config file it's trying to verify.

It uses gitlab-runner verify on the temp config file. 

I think if you check that temp config file, then you should be able to see what's wrong with the config output.

**Comment by netcitylife** [comment]
Here is my tmp config:
```
[root@pbx fail2ban]# cat /tmp/ansible.raFVzVgitlab-runner-config/gitlab-runner.1.nCVTHY
  name = "pbx.***.ee"
  limit = 0
  output_limit = 4096
  url = "https://gitlab.***.ru/"
  token = "***"
  executor = "shell"
  [runners.shell]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.gcs]
  environment = []
```

**Comment by richard-to** [comment]
I believe the issue maybe the `[runners.shell]` section.

But that issue seems like it was recently resolved here: https://github.com/riemers/ansible-gitlab-runner/pull/86

**Comment by riemers** [comment]
Let me push out a release then, since it was not in a release bundle yet

**Comment by netcitylife** [comment]
Hi. Thank you for the fix, but v1.5.3 is still not available at Ansible Galaxy...

**Comment by riemers** [comment]
It is there now, the import failed on the galaxy side, presume some hickup. Did manual trigger and it is there now ;)

**Comment by netcitylife** [comment]
Works good now, thanks!
